### ISSUE TITLE
Async failing either ways

### ISSUE THREAD

**Issue by HassanGulzar** [jweber/WcfClientProxyGenerator#19]
I'm trying to call the Async version of the APIs I have but regardless of the the way I cook a proxy `proxyLookupAsync = (WcfClientProxy.CreateAsyncProxy<ILookupService>` or  `proxyLookup = WcfClientProxy.Create<ILookupService>`), I get this exception once I call an API: 

> System.NotSupportedException: 
Method GetCompaniesAsync is not supported on this proxy, this can happen if the method is not marked with OperationContractAttribute or if the interface type is not marked with ServiceContractAttribute.

Here is my contract:
```
using DA.Services.CarPark.ServiceCommon;
using System.Collections.Generic;
using System.ServiceModel;

namespace DA.Services.CarPark.ServiceContracts.Common.v1
{

    [ServiceContract(Namespace = Constants.ServiceNamespace)]
    public interface ILookupService
    {

        [OperationContract]
        [FaultContract(typeof(CarParkFault))]
        IList<BDO.Company> GetCompanies();

    }
}
```

Here is `CarParkFault`

```
using System.Runtime.Serialization;

namespace DA.Services.CarPark.ServiceCommon
{
    [DataContract]
    public class CarParkFault
    {
        [DataMember]
        public string FaultMessage;

        public CarParkFault(string ErrMessage)
        {
            FaultMessage = ErrMessage;
        }
    }
}
```

And `Constants.ServiceNamespace` is:

`public const string ServiceNamespace = "http://www.myairports.ae/internal/services/";`

What am I missing here?

**Comment by jweber** [comment]
It looks like your issue was due to the trailing '/' on the ServiceNamespace being used. The code wasn't de-duplicating the trailing slash when the proxy was generated which caused the Async OperationContract method to be mismatched from the synchronous implementation.

I'll try to get a build out soon that includes the fix but in the meantime removing the trailing slash from your namespace should fix the issue. 

Thanks for the detailed error report!

**Comment by jweber** [comment]
v2.2.1 has been pushed out to NuGet. Let me know if that works for you.

**Comment by HassanGulzar** [comment]
I'll do that first thing tomorrow!

**Comment by HassanGulzar** [comment]
Ok. I took the latest repo code and also removed the trailing '/' and tried against an updated publish of my service and I'm still having the same issue.

**Comment by HassanGulzar** [comment]
I have tried removing the namespace completely, and tried without specifying any faults. I'm getting the same exception. I'm working primarily with the CallAsync API.

**Comment by jweber** [comment]
The trailing slash thing was definitely _an_ issue, so I'm glad we were able to get that fixed at least!

Unfortunately, I can't recreate the issue you are currently seeing. Here's the test case I was using in which I pulled in your example code. Could you take a look at it and see if there's anything different there than in how you're using it?

https://gist.github.com/jweber/04b65fe9c9c8aa0417c9ae3d10185b7d

**Comment by HassanGulzar** [comment]
I'm trying to go through the test right now. Unfortunately I don't have direct access tot he actual service I have at office on intranet but since I wrote the service, I should be facing the same issue as I don't spot any difference. I'll prep the execution now.

**Comment by HassanGulzar** [comment]
Okay. After a long while, I was able to complete my test. I'm attaching a solution that fails and reflects my actual project as much as possible. 

A few things:

- .Net Framework 4.6.1
- x64 for all projects for the Any CPU config
- Service is hosted in IIS

[ExecutionPoint.zip](https://github.com/jweber/WcfClientProxyGenerator/files/251127/ExecutionPoint.zip)

**Comment by jweber** [comment]
Thanks for that detailed recreation. I was able to track it down to creating the proxy using the `c.SetEndpoint("BasicHttpBinding_ILookupService")` configuration option. Using that method to create the proxy wasn't creating the WCF channel with the correct service contract.

I've pushed out a fix as version 2.2.2. Give that a shot and let me know if it works for you.

**Comment by HassanGulzar** [comment]
After simply updating the nuget package, I still get the exception.

**Comment by HassanGulzar** [comment]
I did not find any luck by completely switching to coded client config so I can use another constructor flavor besides the `c.SetEndpoint("testServiceConfiguration");`

I'm attaching a modified project. i hope you have better luck
[ExecutionPoint.zip](https://github.com/jweber/WcfClientProxyGenerator/files/253090/ExecutionPoint.zip)
 then me.

**Comment by jweber** [comment]
Ah, you're right. Looks like the buildserver packaged the 2.2.1 binary in the 2.2.2 NuGet package. I just pushed out a new version 2.2.3 to NuGet and verified it contains the correct binary. I confirmed that upgrading to 2.2.3 from NuGet works against your test project.

Give that another shot when you have a chance.

**Comment by HassanGulzar** [comment]
Just did. But I'm still facing the same issue. Do I need to clear some kind of cache?

**Comment by jweber** [comment]
Oh, I just saw you tried another version of `c.SetEndpoint()` and it was still having issues. I'm taking a look at your latest example now.

**Comment by HassanGulzar** [comment]
Ok

**Comment by HassanGulzar** [comment]
So I reverted to the other constructor and can confirm it finally works!

**Comment by jweber** [comment]
That's good news! I also see what the issue is with your latest example but I don't have a quick fix for it yet.

Using the `SetEndpoint(ServiceEndpoint)` constructor is taking the ServiceEndpoint object you're creating where you specify the contract as being `ContractDescription.GetContract(typeof(ILookupService))`. The WcfClientProxyGenerator code actually needs to swap out the `ILookupService` contract with a contract it generates at runtime (named `ILookupServiceAsync`). I'll take a stab at getting that working later.

I'm glad it's finally operating as expected for you. I'll go ahead and close this issue.

**Comment by HassanGulzar** [comment]
Perfect
